=== eth-cscs/sarus/etc/sarus.schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema#",
    "title": "Sarus",
    "description": "Sarus configuration file",
    "type": "object",
    "properties": {
        "securityChecks": {
            "type": "boolean"
        },
        "OCIBundleDir": {
            "$ref": "definitions.schema.json#/AbsolutePath"
        },
        "rootfsFolder": {
            "$ref": "definitions.schema.json#/Folder"
        },
        "prefixDir": {
            "$ref": "definitions.schema.json#/AbsolutePath"
        },
        "hooksDir": {
            "$ref": "definitions.schema.json#/AbsolutePath"
        },
        "tempDir": {
            "$ref": "definitions.schema.json#/AbsolutePath"
        },
        "localRepositoryBaseDir": {
            "$ref": "definitions.schema.json#/AbsolutePath"
        },
        "centralizedRepositoryDir": {
            "$ref": "definitions.schema.json#/AbsolutePath"
        },
        "skopeoPath": {
            "$ref": "definitions.schema.json#/AbsolutePath"
        },
        "umociPath": {
            "$ref": "definitions.schema.json#/AbsolutePath"
        },
        "mksquashfsPath": {
            "$ref": "definitions.schema.json#/AbsolutePath"
        },
        "mksquashfsOptions": {
            "type": "string"
        },
        "initPath": {
            "$ref": "definitions.schema.json#/AbsolutePath"
        },
        "runcPath": {
            "$ref": "definitions.schema.json#/AbsolutePath"
        },
        "ramFilesystemType": {
            "oneOf": [
                {
                    "type": "string",
                    "pattern": "^ramfs$"
                },
                {
                    "type": "string",
                    "pattern": "^tmpfs$"
                }
            ]
        },
        "siteMounts": {
            "$ref": "#/definitions/ArrayOfMounts"
        },
        "siteDevices": {
            "$ref": "#/definitions/ArrayOfDevices"
        },
        "environment": {
            "type": "object",
            "properties": {
                "set": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "prepend": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "append": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "unset": {
                    "$ref": "definitions.schema.json#/ArrayOfStrings"
                }
            }
        },
        "userMounts": {
            "type": "object",
            "properties": {
                "notAllowedPrefixesOfPath": {
                    "$ref": "definitions.schema.json#/ArrayOfAbsolutePaths"
                },
                "notAllowedPaths": {
                    "$ref": "definitions.schema.json#/ArrayOfAbsolutePaths"
                }
            },
            "required":[ "notAllowedPrefixesOfPath", "notAllowedPaths" ]
        },
        "seccompProfile": {
            "$ref": "definitions.schema.json#/AbsolutePath"
        },
        "apparmorProfile": {
            "type": "string"
        },
        "selinuxLabel": {
            "type": "string"
        },
        "selinuxMountLabel": {
            "type": "string"
        },
        "containersPolicy": {
            "$ref": "#/definitions/ContainersPolicy"
        },
        "containersRegistries.dPath": {
            "$ref": "definitions.schema.json#/AbsolutePath"
        },
        "enablePMIxv3Support": {
            "type": "boolean"
        }
    },
    "required": [
        "securityChecks",
        "OCIBundleDir",
        "rootfsFolder",
        "prefixDir",
        "tempDir",
        "localRepositoryBaseDir",
        "skopeoPath",
        "umociPath",
        "mksquashfsPath",
        "initPath",
        "runcPath",
        "ramFilesystemType"
    ],
    "definitions": {
        "Mount": {
            "type": "object",
            "properties": {
                "type": {
                    "oneOf": [
                        {
                            "type": "string",
                            "pattern": "^bind$"
                        }
                    ]
                },
                "source": {
                    "$ref": "definitions.schema.json#/AbsolutePath"
                },
                "destination": {
                    "$ref": "definitions.schema.json#/AbsolutePath"
                },
                "flags": {
                    "type": "object",
                    "properties": {
                        "readonly": {
                            "type": "string",
                            "pattern": ""
                        },
                        "size": {
                            "type": "string",
                            "pattern": "^[0-9]+[BKMGTPE]$"
                        },
                        "bs": {
                            "type": "string",
                            "pattern": "^[0-9]+[BKMGTPE]$"
                        }
                    }
                }
            },
            "required": [
                "type",
                "destination"
            ]
        },
        "Device": {
            "type": "object",
            "properties": {
                "source": {
                    "$ref": "definitions.schema.json#/AbsolutePath"
                },
                "destination": {
                    "$ref": "definitions.schema.json#/AbsolutePath"
                },
                "access": {
                    "type": "string",
                    "pattern": "^[rwm]{,3}$"
                }
            },
            "required": [
                "source"
            ]
        },
        "ArrayOfMounts": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/Mount"
            }
        },
        "ArrayOfDevices": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/Device"
            }
        },
        "ContainersPolicy": {
            "type": "object",
            "properties": {
                "path": {
                    "$ref": "definitions.schema.json#/AbsolutePath"
                },
                "enforce": {
                    "type": "boolean"
                }
            },
            "required": [
                "path"
            ]
        }
    }
}

=== eth-cscs/sarus/src/common/test/json/min_required.json
{
    "securityChecks": false,
    "OCIBundleDir": "/var/sarus/OCIBundleDir",
    "rootfsFolder": "rootfsFolder",
    "prefixDir": "/opt/sarus",
    "tempDir": "/tmp",
    "localRepositoryBaseDir" : "/home",
    "skopeoPath": "/usr/bin/skopeo",
    "umociPath": "/usr/bin/umoci",
    "mksquashfsPath": "/usr/sbin/mksquashfs",
    "initPath": "/opt/sarus/bin/init",
    "runcPath": "/usr/bin/runc.amd64",
    "ramFilesystemType": "tmpfs"
}
